substitutions:
  _IMAGE_NAME: firely-example
  
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-docker.pkg.dev/${PROJECT_ID}/gcr.io/${_IMAGE_NAME}:${BRANCH_NAME}'
      - '-f'
      - 'deploy/Dockerfile'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-docker.pkg.dev/${PROJECT_ID}/gcr.io/${_IMAGE_NAME}:${BRANCH_NAME}'